apiVersion: v1
kind: ServiceAccount
metadata:
  name: batch-gw-operator-controller-manager
  namespace: system
  labels:
    app.kubernetes.io/name: batch-gw-operator
    app.kubernetes.io/managed-by: kustomize
